In [1]:
import pandas as pd
import json
import xml.etree.ElementTree as ET
import requests

In [2]:
api_url = 'https://jsonplaceholder.typicode.com/users' 
response = requests.get(api_url)
data = response.json()
df_jsonormal = pd.json_normalize(data) #Separa o aninhamento do adress em suas colunas especificas
df_json = pd.DataFrame(data) # nao normalizado (adress contem alinhamento)
df_jsonormal

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,1-477-935-8478 x6430,ola.org,Norberto Crossing,Apt. 950,South Christy,23505-1337,-71.4197,71.7478,Considine-Lockman,Synchronised bottom-line interface,e-enable innovative applications
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,210.067.6132,elvis.io,Rex Trail,Suite 280,Howemouth,58804-1099,24.8918,21.8984,Johns Group,Configurable multimedia task-force,generate enterprise e-tailers
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,586.493.6943 x140,jacynthe.com,Ellsworth Summit,Suite 729,Aliyaview,45169,-14.3990,-120.7677,Abernathy Group,Implemented secondary concept,e-enable extensible e-tailers
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,(775)976-6794 x41206,conrad.com,Dayna Park,Suite 449,Bartholomebury,76495-3109,24.6463,-168.8889,Yost and Sons,Switchable contextually-based project,aggregate real-time technologies
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,024-648-3804,ambrose.net,Kattie Turnpike,Suite 198,Lebsackbury,31428-2261,-38.2386,57.2232,Hoeger LLC,Centralized empowering task-force,target end-to-end models

In [3]:
nested = {
    'nome': 'x',
    'email': 'x@gmail.com',
    'adress': {
        'rua':'rua123',
        'cidade': 'CidadeCity',
        'cep': '12345678910'
    }
}
df = pd.json_normalize(nested)
df

  nome        email adress.rua adress.cidade   adress.cep
0    x  x@gmail.com     rua123    CidadeCity  12345678910

In [4]:
df_json['company'] = None
df_clean = df_json.dropna(axis=1) # axis=1 - elimina a coluna inteira, significa eixo vertical
df_limpo = df_json.fillna('Nao existe', inplace=True)

In [5]:
df_json_exlpoded = df_json.explode('address')
df_json_exlpoded

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,street,1-770-736-8031 x56442,hildegard.org,Nao existe
0,1,Leanne Graham,Bret,Sincere@april.biz,suite,1-770-736-8031 x56442,hildegard.org,Nao existe
0,1,Leanne Graham,Bret,Sincere@april.biz,city,1-770-736-8031 x56442,hildegard.org,Nao existe
0,1,Leanne Graham,Bret,Sincere@april.biz,zipcode,1-770-736-8031 x56442,hildegard.org,Nao existe
0,1,Leanne Graham,Bret,Sincere@april.biz,geo,1-770-736-8031 x56442,hildegard.org,Nao existe
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,street,010-692-6593 x09125,anastasia.net,Nao existe
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,suite,010-692-6593 x09125,anastasia.net,Nao existe
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,city,010-692-6593 x09125,anastasia.net,Nao existe
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,zipcode,010-692-6593 x09125,anastasia.net,Nao existe
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,geo,010-692-6593 x09125,anastasia.net,Nao existe
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,street,1-463-123-4447,ramiro.info,Nao existe
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,suite,1-463-123-4447,ramiro.info,Nao existe
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,city,1-463-123-4447,ramiro.info,Nao existe
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,zipcode,1-463-123-4447,ramiro.info,Nao existe
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,geo,1-463-123-4447,ramiro.info,Nao existe
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,street,493-170-9623 x156,kale.biz,Nao existe
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,suite,493-170-9623 x156,kale.biz,Nao existe
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,city,493-170-9623 x156,kale.biz,Nao existe
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,zipcode,493-170-9623 x156,kale.biz,Nao existe
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,geo,493-170-9623 x156,kale.biz,Nao existe
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,street,(254)954-1289,demarco.info,Nao existe
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,suite,(254)954-1289,demarco.info,Nao existe
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,city,(254)954-1289,demarco.info,Nao existe
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,zipcode,(254)954-1289,demarco.info,Nao existe
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,geo,(254)954-1289,demarco.info,Nao existe
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,street,1-477-935-8478 x6430,ola.org,Nao existe
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,suite,1-477-935-8478 x6430,ola.org,Nao existe
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,city,1-477-935-8478 x6430,ola.org,Nao existe
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,zipcode,1-477-935-8478 x6430,ola.org,Nao existe
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,geo,1-477-935-8478 x6430,ola.org,Nao existe
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,street,210.067.6132,elvis.io,Nao existe
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,suite,210.067.6132,elvis.io,Nao existe
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,city,210.067.6132,elvis.io,Nao existe
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,zipcode,210.067.6132,elvis.io,Nao existe
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,geo,210.067.6132,elvis.io,Nao existe
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,street,586.493.6943 x140,jacynthe.com,Nao existe
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,suite,586.493.6943 x140,jacynthe.com,Nao existe
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,city,586.493.6943 x140,jacynthe.com,Nao existe
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,zipcode,586.493.6943 x140,jacynthe.com,Nao existe
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,geo,586.493.6943 x140,jacynthe.com,Nao existe
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,street,(775)976-6794 x41206,conrad.com,Nao existe
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,suite,(775)976-6794 x41206,conrad.com,Nao existe
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,city,(775)976-6794 x41206,conrad.com,Nao existe
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,zipcode,(775)976-6794 x41206,conrad.com,Nao existe
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,geo,(775)976-6794 x41206,conrad.com,Nao existe
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,street,024-648-3804,ambrose.net,Nao existe
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,suite,024-648-3804,ambrose.net,Nao existe
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,city,024-648-3804,ambrose.net,Nao existe
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,zipcode,024-648-3804,ambrose.net,Nao existe
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,geo,024-648-3804,ambrose.net,Nao existe

In [6]:
xml_data = """
<data>
    <user>
        <name>joao</name>
        <email>joao@gmail.com</email>
        <cidade>santo andre</cidade>
    </user>
    <user>
        <name>maria</name>
        <email>maria@gmail.com</email>
        <!-- Nao existe -->
    </user>
</data>
"""

root = ET.fromstring(xml_data)
users = []

for user in root.findall("user"):
    users.append({
        'name':user.find('name').text if user.find('name') is not None else None,
        'email':user.find('email').text if user.find('email') is not None else None,
        'cidade':user.find('cidade').text if user.find('cidade') is not None else None

    })

df_xml = pd.DataFrame(users)
df_xml

    name            email       cidade
0   joao   joao@gmail.com  santo andre
1  maria  maria@gmail.com         None

In [7]:

print('Antes')
df_dups = pd.DataFrame({'id': [1,1,2,3], 'name': ['Alice', 'Alice', 'Bob', 'Charlie']})
df_dups

df_unico = df_dups.drop_duplicates()

print('Depois')
df_unico

Antes
Depois

   id     name
0   1    Alice
2   2      Bob
3   3  Charlie

In [8]:
df_padrao = pd.DataFrame({'datas': ['2023-02-12', 'Feb 24, 2024', '2011/11/11']})

df_padrao['datas'] = pd.to_datetime(df_padrao['datas'], format='mixed')

print(df_padrao)

       datas
0 2023-02-12
1 2024-02-24
2 2011-11-11

In [9]:
with open('data.json', 'r', encoding='utf-8') as f:
    data_arq = json.load(f)

data_arq[1]

FileNotFoundError: [Errno 2] No such file or directory: 'data.json'

In [ ]:
print('chaves', data_arq[0].keys())

chaves dict_keys(['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes', 'categories', 'hours'])

In [ ]:
df_yelp = pd.json_normalize(data_arq)
df_yelp.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,attributes.AcceptsInsurance,attributes.BestNights,attributes.BYOB,attributes.Corkage,attributes.BYOBCorkage,attributes.HairSpecializesIn,attributes.Open24Hours,attributes.RestaurantsCounterService,attributes.AgesAllowed,attributes.DietaryRestrictions
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_yelpcustom = pd.DataFrame([{
    'business_id': d.get('business_id'),
    'name': d.get('name'),
    'city': d.get('city'),
    'review_count': d.get('review_count'),
    'stars': d.get('stars'),
    'categories': d.get('categories')
}for d in data_arq])

print(df_yelpcustom.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   city          150346 non-null  object
 3   review_count  150346 non-null  int64
 4   stars         150346 non-null  float64
 5   categories    150243 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.9+ MB
None

In [ ]:
df_yelpcustom.fillna('Desconhecido', inplace=True)
print(df_yelpcustom.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   city          150346 non-null  object
 3   review_count  150346 non-null  int64
 4   stars         150346 non-null  float64
 5   categories    150346 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.9+ MB
None

In [ ]:
df_yelpatri = pd.DataFrame([
    {
        'business_id': d.get('business_id'),
        'Wifi': ( d.get('attributes') or {} ).get('Wifi', 'Unknown'),
        'OutdoorSeating': ( d.get('attributes') or {} ).get('OutdoorSeating', 'Unknown'),
    } for d in data_arq])

print(df_yelpatri)

                   business_id     Wifi OutdoorSeating
0       Pns2l4eNsfO8kk83dixA6A  Unknown        Unknown
1       mpf3x-BjTdTEA3yCZrAYPw  Unknown        Unknown
2       tUFrWirKiKi_TAnsVWINQQ  Unknown          False
3       MTSW4McQd7CbVtyjqoe9mw  Unknown          False
4       mWMc6_wTdE0EUBKIGXDVfA  Unknown        Unknown
...                        ...      ...            ...
150341  IUQopTMmYQG-qRtBk-8QnA  Unknown        Unknown
150342  c8GjPIOTGVmIemT7j5_SyQ  Unknown        Unknown
150343  _QAMST-NrQobXduilWEqSw  Unknown        Unknown
150344  mtGm22y5c2UHNXDFAjaPNw  Unknown        Unknown
150345  jV_XOycEzSlTx-65W906pg  Unknown        Unknown

[150346 rows x 3 columns]

In [ ]:
data_arq[0].keys()

dict_keys(['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes', 'categories', 'hours'])

In [ ]:
weekdays = ['Sunday','Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

df_horario = pd.DataFrame([
    {
        'business_id': d.get('business_id'),
        **{day: (d.get('hours') or {}).get(day, 'Fechado')   for day in weekdays}
}for d in data_arq])

print(df_horario.head())

              business_id     Sunday    Monday    Tuesday  Wednesday  \
0  Pns2l4eNsfO8kk83dixA6A    Fechado   Fechado    Fechado    Fechado
1  mpf3x-BjTdTEA3yCZrAYPw    Fechado   0:0-0:0  8:0-18:30  8:0-18:30
2  tUFrWirKiKi_TAnsVWINQQ   8:0-22:0  8:0-22:0   8:0-22:0   8:0-22:0
3  MTSW4McQd7CbVtyjqoe9mw   7:0-21:0  7:0-20:0   7:0-20:0   7:0-20:0
4  mWMc6_wTdE0EUBKIGXDVfA  12:0-18:0   Fechado    Fechado  14:0-22:0

    Thursday     Friday   Saturday
0    Fechado    Fechado    Fechado
1  8:0-18:30  8:0-18:30   8:0-14:0
2   8:0-22:0   8:0-23:0   8:0-23:0
3   7:0-20:0   7:0-21:0   7:0-21:0
4  16:0-22:0  12:0-22:0  12:0-22:0

In [ ]:
#df_yelpatri df_yelpcustom df_horario

df_merge = df_yelpcustom.merge(df_yelpatri, on='business_id', how='left')
df_merge = df_merge.merge(df_horario, on='business_id', how='left')

df_merge.info()

In [ ]:
df_merge_explode = df_merge.assign(categories=df_merge["categories"].str.split(', '))

In [ ]:
df_merge_explode = df_merge_explode.explode('categories')
df_merge_explode

In [ ]:
df_restaurants = df_merge_explode[df_merge_explode['categories'] == 'Restaurants']
len(df_restaurants)

52268